In [2]:
#project Studnet marks Analysis System
# This walkthrough build small ,realistic pipeline using numpy
# dataset creation
#average marks per student 
#highrst and lowest marks
# Standard deviation per student 
#Ranking student
#Top Student (above class average)
#Subjects wise analysis
#percentage calculation
#visuallization ready data

In [5]:
import numpy as np

students = np.array(["Bibek", "Govind", "Hitesh", "Suraj", "Deba"])
subjects = np.array(["Math", "Science", "English", "Computer"])

marks = np.array([
    [85, 90, 78, 88],
    [72, 68, 75, 70],
    [95, 92, 90, 96],
    [60, 65, 58, 62],
    [88, 84, 91, 86]
])
print("Students:", students)
print("Subjects:", subjects)
print("Marks:\n", marks)

Students: ['Bibek' 'Govind' 'Hitesh' 'Suraj' 'Deba']
Subjects: ['Math' 'Science' 'English' 'Computer']
Marks:
 [[85 90 78 88]
 [72 68 75 70]
 [95 92 90 96]
 [60 65 58 62]
 [88 84 91 86]]


In [6]:
average = np.mean(marks, axis=1)

print("Average Marks")
for name, avg in zip(students, average):
    print(name, ":", avg)

Average Marks
Bibek : 85.25
Govind : 71.25
Hitesh : 93.25
Suraj : 61.25
Deba : 87.25


In [7]:
highest = np.max(marks, axis=1)
lowest = np.min(marks, axis=1)

for i in range(len(students)):
    print(students[i],
          "Highest =", highest[i],
          "Lowest =", lowest[i])

Bibek Highest = 90 Lowest = 78
Govind Highest = 75 Lowest = 68
Hitesh Highest = 96 Lowest = 90
Suraj Highest = 65 Lowest = 58
Deba Highest = 91 Lowest = 84


In [8]:
std = np.std(marks, axis=1)

for name, s in zip(students, std):
    print(name, ":", round(s,2))

Bibek : 4.55
Govind : 2.59
Hitesh : 2.38
Suraj : 2.59
Deba : 2.59


In [9]:
average = np.mean(marks, axis=1)

ranking = np.argsort(-average)

print("Ranking")
for rank, idx in enumerate(ranking, start=1):
    print(rank, students[idx], average[idx])

Ranking
1 Hitesh 93.25
2 Deba 87.25
3 Bibek 85.25
4 Govind 71.25
5 Suraj 61.25


In [10]:
student_avg = np.mean(marks, axis=1)

class_avg = np.mean(student_avg)

print("Class Average =", class_avg)
top_students = students[student_avg > class_avg]
print("Top Students:")
print(top_students)

Class Average = 79.65
Top Students:
['Bibek' 'Hitesh' 'Deba']


In [11]:
subject_average = np.mean(marks, axis=0)

for sub, avg in zip(subjects, subject_average):
    print(sub, ":", avg)

Math : 80.0
Science : 79.8
English : 78.4
Computer : 80.4
