In [2]:
import numpy as np
print(np.__version__)

2.3.5


In [3]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [9]:
import numpy as np

c = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(a)
print(c.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [12]:
d = np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
e = np.ones((3,4))
print(e)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
a= np.array([1,2,3])
print(a.dtype)

int64


In [26]:
b = np.array([1,2,3], dtype = np.float32)
print(b.dtype)

float32


In [30]:
c =  a.astype(np.float64)
print(c.dtype)

float64


In [32]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64


In [33]:
a = np.arange(12)
print(a)
b= a.reshape(3,4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
c= a.reshape(2,-1)
print(c)
print(c.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)


In [36]:
arr1 = np.array([[1,2],[3,4]])
print(arr)
print(arr.flatten())
print(arr.ravel)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
<built-in method ravel of numpy.ndarray object at 0x000002ADDDBD3810>


In [40]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

print(a+b)
print(a-b)
print(a * b)
print(a / b)
print(a % b)
print(a ** 2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[0 0 0 0]
[ 100  400  900 1600]


In [42]:
a = np.array([1,2,3,4])
b= np.array([4,3,2,1])
print( a> b)
print( a == b)
print(a <= b)

[False False  True  True]
[False False False False]
[ True  True False False]


In [44]:
a = np.array([1,2,3,4])
b= np.array([4,3,2,1])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.power(a,b))
print(np.mod(a,b))
print(np.abs(np.array([-1,-2,3])))

[5 5 5 5]
[-3 -1  1  3]
[4 6 6 4]
[0.25       0.66666667 1.5        4.        ]
[1 8 9 4]
[1 2 1 0]
[1 2 3]


In [45]:
a= np.array([10,20,30,40,50])
print(a[0])
print(a[3])

b= np.array([[1,2,3],[4,5,6]])
print(b[1,2])

10
40
6


In [47]:
a= np.arange(10)
print(a[::2])
print(a[1:8:2])
print(a[::-1])

[0 2 4 6 8]
[1 3 5 7]
[9 8 7 6 5 4 3 2 1 0]


In [49]:
a = np.array([10,20,30,40,50])
idx = [0,2,4]
print(a[idx])

[10 30 50]


In [54]:
a = np.array([10,15,20,25,30])
print(a)
mask =a >18
print(mask)
print(a[mask])
print(a[a % 10== 0])

[10 15 20 25 30]
[False False  True  True  True]
[20 25 30]
[10 20 30]


In [56]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print( np.sum(a))
print( np.mean(a))
print( np.median(a))
print( np.std(a))
print( np.var(a))
print( np.min(a))
print( np.max(a))
print( np.percentile(a,75))
print( np.sqrt(a))
print( np.log(a))
print( np.exp(a))
print( np.sin(a))

55
5.5
5.5
2.8722813232690143
8.25
1
10
7.75
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]


In [57]:
a = np.array([1,2,3])
b= np.array([4,5,6])

print(a)
print(b)
print(np.concatenate([a,b]))
print(np.stack([a,b]))
print(np.hstack([a,b]))
print(np.stack([a,b],axis=0))

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [63]:
a = np.arange(9)
print(a)
print(np.split(a,3))

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [64]:
a = np.arange(9)
print(a)
print(np.split(a,9))

[0 1 2 3 4 5 6 7 8]
[array([0]), array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8])]


In [66]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [69]:
print(np.append(a , [4,5]))
print(a)

[1 2 3 4 5]
[1 2 3]


In [70]:
print(np.insert(a,1,99))
print(a)

[ 1 99  2  3]
[1 2 3]


In [73]:
c= print(np.delete(a,0))
print(a)


[2 3]
[1 2 3]


In [75]:
a = np.array([3,1,4,1,5,9,2])

print(a)
b= np.sort(a)
print(b)

[3 1 4 1 5 9 2]
[1 1 2 3 4 5 9]


In [79]:
a = np.array([3,1,4,1,5,9,2])
print(a)
print(np.unique(a))
print(a)
b=a[::-1]
print(a)
print(b)


[3 1 4 1 5 9 2]
[1 2 3 4 5 9]
[3 1 4 1 5 9 2]
[3 1 4 1 5 9 2]
[2 9 5 1 4 1 3]
